### ISSUE TITLE
gpu specifications

### ISSUE THREAD

**Issue by rkdckddnjs9** [NotACracker/COTR#1]
Thank you for your great work.
My gpu is 3090, but memory overflow occurs. 
Could you tell me the gpu specifications you used in the experiment?

**Comment by NotACracker** [comment]
> Thank you for your great work. My gpu is 3090, but memory overflow occurs. Could you tell me the gpu specifications you used in the experiment?

We default to using 4 RTX A6000 with  2 batch per gpu
