### ISSUE TITLE
How COTR is integrated with the baselines

### ISSUE THREAD

**Issue by LeeKeyu** [NotACracker/COTR#4]
Thanks for your great and impressive work! I am wondering if you can elaborate more on how the COTR is integrated with several baseline methods BEVDet4D [8], TPVFormer [10], SurroundOcc [37] and OccFormer [41], as this seems not clearly described in the paper or code. 
During reading the paper, I thought COTR itself was an alternative to the baseline methods, e.g., TPVFormer, SurroundOcc, which shared the same input and output as COTR. So I was really confused by the statement that the COTR was integrated with the aforementioned methods to obtain the results shown in the paper.  I suppose that it would be very helpful to understand the information flow and changes of these methods by integrating COTR. 
Thanks a lot in advance! Your advice will of great help to me and other potential readers.

**Comment by NotACracker** [comment]
> Thanks for your great and impressive work! I am wondering if you can elaborate more on how the COTR is integrated with several baseline methods BEVDet4D [8], TPVFormer [10], SurroundOcc [37] and OccFormer [41], as this seems not clearly described in the paper or code. During reading the paper, I thought COTR itself was an alternative to the baseline methods, e.g., TPVFormer, SurroundOcc, which shared the same input and output as COTR. So I was really confused by the statement that the COTR was integrated with the aforementioned methods to obtain the results shown in the paper. I suppose that it would be very helpful to understand the information flow and changes of these methods by integrating COTR. Thanks a lot in advance! Your advice will of great help to me and other potential readers.

We have provided configuration files for integrating COTR into SurroundOCC or Occformer, which can be found in configs/cotr/.

**Comment by LeeKeyu** [comment]
ok thanks. I will look into the code.

**Comment by duoduozi-seu** [comment]
> 感谢您出色而令人印象深刻的工作！我想知道您是否可以更详细地说明 COTR 如何与几种基线方法 BEVDet4D [8]、TPVFormer [10]、SurroundOcc [37] 和 OccFormer [41] 集成，因为这似乎在论文或代码中没有明确描述。 在阅读论文时，我认为 COTR 本身是基线方法的替代品，例如 TPVFormer、SurroundOcc，它们与 COTR 共享相同的输入和输出。所以我对 COTR 与上述方法集成以获得论文中显示的结果的说法感到非常困惑。我认为通过集成 COTR 来了解这些方法的信息流和变化将非常有帮助。 提前谢谢！您的建议对我和其他潜在读者将大有帮助。

我只找到了cotr与occFormer等集成的配置文件，没有找到单独的COTR的配置文件，因为我想训练原本的cotr网络，请问您找到了么，能不能告知一下？或者说这个配置文件需要自己写？本人水平十分有限，提出这些十分幼稚的问题请见谅

**Comment by duoduozi-seu** [comment]
> > 感谢您出色而令人印象深刻的工作！我想知道您是否可以更详细地说明 COTR 如何与几种基线方法 BEVDet4D [8]、TPVFormer [10]、SurroundOcc [37] 和 OccFormer [41] 集成，因为这似乎在论文或代码中没有明确描述。在阅读论文时，我认为 COTR 本身是基线方法的替代品，例如 TPVFormer、SurroundOcc，它们与 COTR 共享相同的输入和输出。所以我对 COTR 与上述方法集成以获得论文中显示的结果的说法感到非常困惑。我认为通过集成 COTR 来了解这些方法的信息流和变化将非常有帮助。提前谢谢！您的建议对我和其他潜在读者将大有帮助。
> 
> 我们提供了将 COTR 集成到 SurroundOCC 或 Occformer 的配置文件，可以在 configs/cotr/ 中找到。

请问训练COTR的配置文件在哪里呢，没有在config文件夹中找到。还有就是如果要训练cotr与occformer等集成的模型，是不是需要将配置文件的倒数第二行#load_from="ckpts/bevdet-r50-4d-stereo-cbgs.pth"注释。本人水平十分有限，提出这些十分幼稚的问题请见谅
