### ISSUE TITLE
GPU memory for training

### ISSUE THREAD

**Issue by lvchuandong** [NotACracker/COTR#6]
Thank you for your great work. I want to know why a GFLOPs of 740.89 is not very high, but when training, when the batch size is 1, the GPU used is already 18.2G. I am using 4090, and if the batch size is 2, there will be an out of memory.
[flops.log](https://github.com/user-attachments/files/15954282/flops.log)

**Comment by NotACracker** [comment]
> Thank you for your great work. I want to know why a GFLOPs of 740.89 is not very high, but when training, when the batch size is 1, the GPU used is already 18.2G. I am using 4090, and if the batch size is 2, there will be an out of memory. [flops.log](https://github.com/user-attachments/files/15954282/flops.log)

The increase in memory comes mainly from IVT and Group transformer decoder, you can reduce the memory by modifying the `_dim_` value in config, but there may be a slightly drop in accuracy

**Comment by lvchuandong** [comment]
Thank you very much
